### ISSUE TITLE
`gs_png_download()`: Double backslash

### ISSUE THREAD

**Issue by howardbaek** [jhudsl/ottrpal#120]
When `gs_png_download()` is run inside `include_slide()` with the default `output_dir = knitr::opts_chunk$get("fig.path")`, I see that `outfile` will have double blackslashes: `figure//XX.png`. 

See this line that constructs file path: https://github.com/jhudsl/ottrpal/blob/main/R/gs_png.R#L85

Was this by design to accomodate Windows file paths? Or can we get rid of the extra backslash? 

@muschellij2 @cansavvy

**Comment by muschellij2** [comment]
I think it depends if fig.path has ending /, but // shouldn’t cause any
issues in R (\\ can), but remove them if causes issues.

**Comment by howardbaek** [comment]
Okay, thanks @muschellij2
