### ISSUE TITLE
Functionalize url-check.R

### ISSUE THREAD

**Issue by howardbaik** [jhudsl/ottrpal#152]
https://github.com/jhudsl/ottr-reports/blob/main/scripts/url-check.R

**Comment by howardbaek** [comment]
@cansavvy 

I think this [`test_url()`](https://github.com/jhudsl/ottr-reports/blob/bbb6c6ca17a40674e87e747047d3ddb41f8a72fd/scripts/url-check.R#L43-L63) can be replaced with the `RCurl::url.exists()`?

**Comment by cansavvy** [comment]
Yes! Good call!

**Comment by howardbaek** [comment]
I ended up just using `test_url()` to reduce dependencies.
